### PR TITLE
RSDEV-373 New Gallery pagination

### PR DESCRIPTION
**Pull request by rlamacraft**
Adds a "Load more" button to grid and tree view of the new Gallery. Crucially, this change also includes a new search parameter for the `getUploadedFiles` endpoint that allows for filtering the results based on whether they are folders for populating the move dialog.

### CODE REVIEW

**Comment by mKowalski256** [comment]
Checked at https://rsdev-373-paginating-gallery-11.researchspace.com. 

The `load more` button seems to work fine, but I see the following problem: after using the button, then navigating away and back to the folder, the button seems to remember it was clicked, but the gallery listing only includes initial page of items. That means I can no longer 'load more' items even though I only see the first page.

**Comment by rlamacraft** [comment]
> after using the button, then navigating away and back to the folder, the button seems to remember it was clicked, but the gallery listing only includes initial page of items. That means I can no longer 'load more' items even though I only see the first page.

Good catch, should be fixed now

**Comment by mKowalski256** [comment]
Also, there seems to be git conficts with latest `main` branch.

**Comment by rlamacraft** [comment]
> Also, there seems to be git conficts with latest `main` branch.

Resolved now

**Review by mKowalski256 — APPROVED** [review]
Tested at https://rsdev-373-paginating-gallery-14.researchspace.com/, looks good to me!

**Pull request merged**
