### PR TITLE
RSDEV-196 Have dependency cruiser check for incompatible licenses

### PR DESCRIPTION
**Pull request by rlamacraft**
This dependency cruiser rule encodes a whitelist of strings of which at least one must appear in the license string of every third-party library we install from npm. As such, by running dependency cruiser, any violations will be reported.

### CODE REVIEW

**Review by tilorspace — COMMENTED** [review]
@rlamacraft do we need to specify GPLv3 explicitly in this allowlist as well or is that accounted for elsewhere?

**Comment by rlamacraft** [comment]
> @rlamacraft do we need to specify GPLv3 explicitly in this allowlist as well or is that accounted for elsewhere?

It's just doing a string matching, so anything with "GPL" will match. If there's a meaningful difference between the two versions then I can look at make the check more sophisticated

**Review by mKowalski256 — APPROVED** [review]
Looks good to me, but are we running dependency-cruiser as a part of any code building workflow? I've run `npx depcruise src` in `src/main/webapp/ui` dir to test the new rule, and license check was fine but the run has shown a pre-existing error for other rule (see [my log](https://github.com/user-attachments/files/16931992/dep-cruise-log-matthias.log)
). I haven't seen that other error reported on jenkins or during react rebuild, which suggest that either it happens just on my local, or it's not run/not failing the builds.

Probably unrelated, but I also cannot get Jest Tests pass on this branch [on jenkins] (https://jenkins.researchspace.com/job/rspace-web/job/rsdev-196-enforce-js-licenses/) (even though I've merged latest `main` branch).

**Comment by rlamacraft** [comment]
> Looks good to me, but are we running dependency-cruiser as a part of any code building workflow?

It does a handle things, of various severity, that are mostly just hints for debugging but as we're using it more and more having it be run with flow is probably a good idea

> Probably unrelated, but I also cannot get Jest Tests pass on this branch

I can't figure out what's going on with those tests; sometimes they start failing consistently and other times it comes and goes, especially on localhost

**Pull request merged**
